/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLBH_CellPhoneS;

import java.awt.Color;
import java.sql.Array;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class FrSuaCTDH_v1 extends javax.swing.JFrame {

    DefaultTableModel tblmodel;
    XuLyDonHang xldh = new XuLyDonHang();

    public FrSuaCTDH_v1() { // OverLoad Contructor ch co tham so
        initComponents();
    }

    PhanQuyen pq;

    public FrSuaCTDH_v1(String maDH, PhanQuyen pq) { // OverLoad Contructor co tham so
        initComponents();
        this.pq = pq;
        this.setTitle("Sửa chi tiết đơn hàng");
        xldh = new XuLyDonHang();
        tblmodel = new DefaultTableModel();
        tblmodel = xldh.themDLchoTablecoDK(tblmodel, "CTDDH", "MaDH", maDH);
        tblCTDH.setModel(tblmodel);
        txtMaSPC.setText(null);
        txtMaSPC.setEditable(false);
        lbSPMoi.setText("MaSP mới:");
        lbSPCu.setText("MaSP cũ: ");
        lbSL.setText("SL thay đổi: ");
        int SelectedRow = tblCTDH.getSelectedRow();
        if (SelectedRow >= 0) {
            txtSL.setText(tblCTDH.getValueAt(tblCTDH.getSelectedRow(), 2).toString());
        }
        pnlThaoTac.setVisible(false);

        lbMaDH.setText(maDH);
        lbNVLap.setText(xldh.lay1DLcoRBTV("HoTenNV", "DonDatHang", "NhanVien", "MaDH", maDH, "MaNV"));
        lbNgayLap.setText(xldh.lay1DL1BangcoDK("NgayLap", "DonDatHang", "MaDH", maDH));
        lbTenKH.setText(xldh.lay1DLcoRBTV("HoTenKH", "DonDatHang", "KhachHang", "MaDH", maDH, "MaKH"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTDH = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbMaDH = new javax.swing.JLabel();
        lbNgayLap = new javax.swing.JLabel();
        lbTenKH = new javax.swing.JLabel();
        lbNVLap = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbTenSP = new javax.swing.JLabel();
        lbMaSp = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnDoi = new javax.swing.JButton();
        btnThaySL = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        pnlThaoTac = new javax.swing.JPanel();
        lbSPMoi = new javax.swing.JLabel();
        lbSL = new javax.swing.JLabel();
        txtMaSPM = new javax.swing.JTextField();
        lbSPCu = new javax.swing.JLabel();
        txtMaSPC = new javax.swing.JTextField();
        txtSL = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        btnCong = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnbTrangChu = new javax.swing.JMenu();
        mnbTroGiup = new javax.swing.JMenu();
        mnbDangXuat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCTDH.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblCTDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCTDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTDHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCTDH);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 153));
        btnBack.setText("Hoàn tất");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("MÃ HÓA ĐƠN:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setText("Tên KH:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setText("NV Lập:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setText("Ngày lập:");

        lbMaDH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMaDH.setForeground(new java.awt.Color(0, 153, 0));
        lbMaDH.setText("--------");

        lbNgayLap.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbNgayLap.setText("--------");

        lbTenKH.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbTenKH.setText("--------");

        lbNVLap.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbNVLap.setText("--------");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMaDH, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lbNgayLap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNVLap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbMaDH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNgayLap)
                .addGap(5, 5, 5)
                .addComponent(lbTenKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNVLap)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("Tình trạng:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("ĐANG CHỈNH SỬA");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("MÃ SẢN PHẨM:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Tên sản phẩm:");

        lbTenSP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTenSP.setText("--------");

        lbMaSp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMaSp.setForeground(new java.awt.Color(0, 153, 0));
        lbMaSp.setText("--------");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMaSp, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lbTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lbMaSp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnDoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoi.setForeground(new java.awt.Color(0, 0, 153));
        btnDoi.setText("Đổi sản phẩm");
        btnDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiActionPerformed(evt);
            }
        });

        btnThaySL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThaySL.setForeground(new java.awt.Color(0, 0, 153));
        btnThaySL.setText("Thay số lượng");
        btnThaySL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThaySLActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(0, 0, 153));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoi, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThaySL, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoi)
                    .addComponent(btnThaySL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlThaoTac.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbSPMoi.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbSPMoi.setText("---------SPMoi");

        lbSL.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbSL.setText("---------SL");

        txtMaSPM.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtMaSPM.setText("1");
        txtMaSPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPMActionPerformed(evt);
            }
        });

        lbSPCu.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbSPCu.setText("---------SPCu");

        txtMaSPC.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        txtSL.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLActionPerformed(evt);
            }
        });

        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(0, 0, 153));
        btnXacNhan.setText("XÁC NHẬN");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnCong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCong.setForeground(new java.awt.Color(0, 0, 153));
        btnCong.setText("+");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });

        btnTru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTru.setForeground(new java.awt.Color(0, 0, 153));
        btnTru.setText("-");
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThaoTacLayout = new javax.swing.GroupLayout(pnlThaoTac);
        pnlThaoTac.setLayout(pnlThaoTacLayout);
        pnlThaoTacLayout.setHorizontalGroup(
            pnlThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThaoTacLayout.createSequentialGroup()
                .addGroup(pnlThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbSPMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(pnlThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSPM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlThaoTacLayout.createSequentialGroup()
                        .addComponent(btnCong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTru))
                    .addGroup(pnlThaoTacLayout.createSequentialGroup()
                        .addComponent(lbSPCu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaSPC, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlThaoTacLayout.setVerticalGroup(
            pnlThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThaoTacLayout.createSequentialGroup()
                .addGroup(pnlThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSPMoi)
                    .addComponent(txtMaSPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSPCu)
                    .addComponent(txtMaSPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSL)
                    .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCong)
                    .addComponent(btnTru)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banner/logocs_1.png"))); // NOI18N
        jPanel6.add(jLabel5);

        mnbTrangChu.setText("Trang chủ");
        mnbTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnbTrangChuMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnbTrangChu);

        mnbTroGiup.setText("Trợ giúp");
        mnbTroGiup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnbTroGiupMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnbTroGiup);

        mnbDangXuat.setText("Đăng xuất");
        mnbDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnbDangXuatMouseClicked(evt);
            }
        });
        mnbDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbDangXuatActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnbDangXuat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel20))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (pq.getXacnhan() == null) {
            this.setVisible(false);
        } else if (pq.getXacnhan() == "2") {
            pq.setXacnhan(null);
            new FrLapHDBH(pq).setVisible(true);
            this.setVisible(false);
        } else {
            pq.setXacnhan(null);
            new FrLapHDBH(pq).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void mnbTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnbTrangChuMouseClicked
        int ques = JOptionPane.showConfirmDialog(this, "Về trang chủ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (ques == 0) {
            new FrQuanLyChung().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_mnbTrangChuMouseClicked

    private void mnbTroGiupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnbTroGiupMouseClicked
        JOptionPane.showMessageDialog(this, "Liên hệ với quản lý để được giải đáp thắc mắc " + "\n" + "Hotline: 19002821");
    }//GEN-LAST:event_mnbTroGiupMouseClicked

    private void mnbDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnbDangXuatMouseClicked
        JOptionPane.showMessageDialog(this, "Bạn đang trong quá trình thêm sản phẩm, vui lòng chọn Button thoát phía dưới để hủy đơn hàng");
        JOptionPane.showMessageDialog(this, "Đăng xuất thất bại !");

    }//GEN-LAST:event_mnbDangXuatMouseClicked

    private void mnbDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbDangXuatActionPerformed
        int ques = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (ques == 0) {
            new FrLogin().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_mnbDangXuatActionPerformed

    private void btnDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiActionPerformed
        pnlThaoTac.setVisible(true);
        txtMaSPM.setEditable(true);
        txtMaSPM.setText("");
        pq.setLuachon("1");
    }//GEN-LAST:event_btnDoiActionPerformed

    private void btnThaySLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThaySLActionPerformed
        txtMaSPM.setEditable(false);
        pnlThaoTac.setVisible(true);
        txtMaSPC.setText(lbMaSp.getText());
        txtMaSPM.setText("-----");
        
        lbSL.setText("SL thay đổi:");
        pq.setLuachon("2");
    }//GEN-LAST:event_btnThaySLActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed

        int dongdcchon = tblCTDH.getSelectedRow();
        int xacnhan = JOptionPane.showConfirmDialog(this, "Bạn muốn thay đổi?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (xacnhan == 0 && (pq.getLuachon().equals("2"))) {
            
            String maHD = tblmodel.getValueAt(dongdcchon, 0).toString();
            String maSP = tblmodel.getValueAt(dongdcchon, 1).toString();

            if (xldh.sua1DL2PKTableRBTV(tblmodel, dongdcchon, "CTDDH", "MaDH", maHD, "MaSP", maSP, "SLMua", txtSL.getText())) {
                tblCTDH.setModel(tblmodel);
                JOptionPane.showMessageDialog(this, "Đã thay đổi SL sản phẩm !");
            }
        } else if (xacnhan == 0 && (pq.getLuachon().equals("1"))) {
            if (xldh.sua2DLFK2PKTable("CTDDH", "MaSP", txtMaSPM.getText().trim(),
                    txtMaSPC.getText(), "SlMua", txtSL.getText().trim(), "MaDH", lbMaDH.getText())) {
                DefaultTableModel tblmodelMoi = new DefaultTableModel();
                tblmodel = xldh.themDLchoTablecoDK(tblmodelMoi, "CTDDH", "MaDH", lbMaDH.getText());
                tblCTDH.setModel(tblmodel);
                JOptionPane.showMessageDialog(this, "Đã thay đổi SL và Mã SP !");
                return ;
            } else {
                JOptionPane.showMessageDialog(this, "Sửa không thành công !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Đã hủy !");
            return;
        }


    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        
        if (tblCTDH.getSelectedRow()<0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng cần xóa !");
            return;
        }
        int ques = JOptionPane.showConfirmDialog(this, "Bạn có thực sự muốn xóa sản phẩm "+lbMaSp.getText()+" ra khỏi đơn hàng ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (ques == 0) {
            xldh.xoa1DongDL1co2DK("CTDDH", "MaDH", tblCTDH.getValueAt(tblCTDH.getSelectedRow(), 0).toString(), "MaSP", tblCTDH.getValueAt(tblCTDH.getSelectedRow(), 1).toString());
            tblmodel.removeRow(tblCTDH.getSelectedRow());
            JOptionPane.showMessageDialog(this, "Đã xóa !");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblCTDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTDHMouseClicked

        String maSP = tblCTDH.getValueAt(tblCTDH.getSelectedRow(), 1).toString();
        lbMaSp.setText(maSP);
        String tenSP = xldh.lay1DL1BangcoDK("TenSP", "SanPham", "MaSP", maSP);
        lbTenSP.setText(tenSP);
        txtSL.setText(tblCTDH.getValueAt(tblCTDH.getSelectedRow(), 2).toString());
        txtMaSPC.setText(lbMaSp.getText());
    }//GEN-LAST:event_tblCTDHMouseClicked

    private void txtSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLActionPerformed

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        String SL = txtSL.getText().trim();
        String cong = String.valueOf(Integer.parseInt(SL) + 1);
        txtSL.setText(cong);
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        String SL = txtSL.getText().trim();
        String tru = String.valueOf(Integer.parseInt(SL) - 1);
        txtSL.setText(tru);
    }//GEN-LAST:event_btnTruActionPerformed

    private void txtMaSPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrSuaCTDH_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrSuaCTDH_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrSuaCTDH_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrSuaCTDH_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrSuaCTDH_v1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnDoi;
    private javax.swing.JButton btnThaySL;
    private javax.swing.JButton btnTru;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMaDH;
    private javax.swing.JLabel lbMaSp;
    private javax.swing.JLabel lbNVLap;
    private javax.swing.JLabel lbNgayLap;
    private javax.swing.JLabel lbSL;
    private javax.swing.JLabel lbSPCu;
    private javax.swing.JLabel lbSPMoi;
    private javax.swing.JLabel lbTenKH;
    private javax.swing.JLabel lbTenSP;
    private javax.swing.JMenu mnbDangXuat;
    private javax.swing.JMenu mnbTrangChu;
    private javax.swing.JMenu mnbTroGiup;
    private javax.swing.JPanel pnlThaoTac;
    private javax.swing.JTable tblCTDH;
    private javax.swing.JTextField txtMaSPC;
    private javax.swing.JTextField txtMaSPM;
    private javax.swing.JTextField txtSL;
    // End of variables declaration//GEN-END:variables
}
