/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLBH_CellPhoneS;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrTaoCTDH extends javax.swing.JFrame {

    DefaultTableModel tblmodel;
    XuLyDonHang xldh = new XuLyDonHang();
    PhanQuyen pq;

    public FrTaoCTDH(PhanQuyen pq, String maDH) {
        this.pq = pq;
        initComponents();
        this.setTitle("Thêm sản phẩm vào hóa đơn ");
        tblmodel = new DefaultTableModel();
        tblmodel.addColumn("Mã sản phẩm");
        tblmodel.addColumn("Tên sản phẩm");
        tblmodel.addColumn("Số lượng");
        tblmodel.addColumn("Hình thức bảo hành");
        tblmodel.addColumn("Đơn giá");
        tblmodel.addColumn("Thành tiền");
        tblHoaDon.setModel(tblmodel);
        txtMaSP.setText("SP0");
        spSL.setValue(1);
        lbMaDH.setText(maDH);
        lbHoTenKH.setText(xldh.thongTinKH(maDH).get(0));
        lbGioiTinhKH.setText(xldh.thongTinKH(maDH).get(1));
        lbNgaySinhKH.setText(xldh.thongTinKH(maDH).get(2));
        lbDienThoaiKH.setText(xldh.thongTinKH(maDH).get(3));
        pnlTTSP.setVisible(false);
    }

    public FrTaoCTDH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbHoTenKH = new javax.swing.JLabel();
        lbGioiTinhKH = new javax.swing.JLabel();
        lbNgaySinhKH = new javax.swing.JLabel();
        lbDienThoaiKH = new javax.swing.JLabel();
        pnl3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        txtMaSP = new javax.swing.JTextField();
        spSL = new javax.swing.JSpinner();
        cbxHTBH1 = new javax.swing.JComboBox<>();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnSua = new javax.swing.JButton();
        btnXoaSP = new javax.swing.JButton();
        btnXemTTSP = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbMaDH = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnlTTSP = new javax.swing.JPanel();
        lbTenSP = new javax.swing.JLabel();
        lbNSX = new javax.swing.JLabel();
        lbNgayRaMat = new javax.swing.JLabel();
        lbBoNho = new javax.swing.JLabel();
        lbXuatXu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnbTrangChu = new javax.swing.JMenu();
        mnbTroGiup = new javax.swing.JMenu();
        mnbDangXuat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setText("Họ tên:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setText("Giới tính:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setText("Ngày sinh:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setText("Điện thoại:");

        lbHoTenKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbHoTenKH.setText("-------");

        lbGioiTinhKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbGioiTinhKH.setText("-------");

        lbNgaySinhKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNgaySinhKH.setText("-------");

        lbDienThoaiKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDienThoaiKH.setText("-------");

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDienThoaiKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbHoTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(lbGioiTinhKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNgaySinhKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbHoTenKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbGioiTinhKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbNgaySinhKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbDienThoaiKH))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setText("MÃ SẢN PHẨM");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setText("Số lượng");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel7.setText("Hình thức bảo hành");

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/THEM.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtMaSP.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        spSL.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        cbxHTBH1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        cbxHTBH1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bảo hành tiêu chuẩn", "Đổi mới 30 ngày miễn phí", "Bảo hành mở rộng" }));

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Reset.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl3Layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addComponent(spSL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(cbxHTBH1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxHTBH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi)
                    .addComponent(btnThem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHoaDon);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banner/logocs.png"))); // NOI18N
        jPanel1.add(jLabel9, new java.awt.GridBagConstraints());

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new java.awt.GridLayout(2, 3, 10, 10));

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/SUA.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel7.add(btnSua);

        btnXoaSP.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnXoaSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/XOA.png"))); // NOI18N
        btnXoaSP.setText("Xóa");
        btnXoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPActionPerformed(evt);
            }
        });
        jPanel7.add(btnXoaSP);

        btnXemTTSP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXemTTSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/TraCuu.png"))); // NOI18N
        btnXemTTSP.setText("Xem TTSP");
        btnXemTTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTTSPActionPerformed(evt);
            }
        });
        jPanel7.add(btnXemTTSP);

        btnLuu.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/LƯU.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel7.add(btnLuu);

        jButton17.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/IN.png"))); // NOI18N
        jButton17.setText("In mẫu");
        jPanel7.add(jButton17);

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/DangXuat.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel7.add(btnThoat);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("HÓA ĐƠN:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(2, 2, 80, 60);

        lbMaDH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMaDH.setForeground(new java.awt.Color(0, 0, 255));
        lbMaDH.setText("---------");
        jPanel3.add(lbMaDH);
        lbMaDH.setBounds(80, 10, 96, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel10.setText("Tên sản phẩm:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel11.setText("Nhà sản xuất:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel12.setText("Ngày ra mắt:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel13.setText("Bộ nhớ:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel14.setText("Xuất xứ:");

        lbTenSP.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbTenSP.setText("--------------------");

        lbNSX.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbNSX.setText("--------------------");

        lbNgayRaMat.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbNgayRaMat.setText("--------------------");

        lbBoNho.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbBoNho.setText("--------------------");

        lbXuatXu.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbXuatXu.setText("--------------------");

        javax.swing.GroupLayout pnlTTSPLayout = new javax.swing.GroupLayout(pnlTTSP);
        pnlTTSP.setLayout(pnlTTSPLayout);
        pnlTTSPLayout.setHorizontalGroup(
            pnlTTSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTSPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbTenSP))
                    .addGroup(pnlTTSPLayout.createSequentialGroup()
                        .addGroup(pnlTTSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbXuatXu)
                            .addComponent(lbNgayRaMat)
                            .addComponent(lbBoNho))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTSPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        pnlTTSPLayout.setVerticalGroup(
            pnlTTSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTSPLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbTenSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNSX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNgayRaMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBoNho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbXuatXu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(pnlTTSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlTTSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mnbTrangChu.setText("Trang chủ");
        mnbTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnbTrangChuMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnbTrangChu);

        mnbTroGiup.setText("Trợ giúp");
        mnbTroGiup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnbTroGiupMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnbTroGiup);

        mnbDangXuat.setText("Đăng xuất");
        mnbDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnbDangXuatMouseClicked(evt);
            }
        });
        mnbDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbDangXuatActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnbDangXuat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addComponent(pnl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPActionPerformed
        int kq = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa ?", "Thông báo ", JOptionPane.YES_NO_OPTION);
        switch (kq) {
            case 0:
                tblmodel.removeRow(tblHoaDon.getSelectedRow());
                break;
            case 1:
                return;
            default:
        }


    }//GEN-LAST:event_btnXoaSPActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtMaSP.setText("");
        spSL.setValue(1);
        cbxHTBH1.setSelectedIndex(0);

    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        xldh = new XuLyDonHang();
        String maSP = txtMaSP.getText();
        if (xldh.lay1DL1BangcoDK("MaSP ", "SanPham", "MaSP", maSP).equals("")) {
            JOptionPane.showMessageDialog(this, "Sai mã sản phẩm!");
            return;
        }
        String tenSP = xldh.lay1DL1BangcoDK("TenSP", "SanPham", "MaSP", maSP);
        String giaBan = (xldh.lay1DL1BangcoDK("GiaBan", "SanPham", "MaSP", maSP));//----
        xldh.setGiaBan(giaBan);
        xldh.setSLMua(spSL.getValue().toString());

        Object ob[] = {maSP, tenSP, spSL.getValue(), cbxHTBH1.getSelectedItem(), xldh.themPhay(giaBan),
            xldh.getThanhTien()};
        tblmodel.addRow(ob);
        xldh.themSPchoTblmodel(tblmodel, 0, 2, 5);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXemTTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTTSPActionPerformed

        xldh = new XuLyDonHang();
        String maSP = tblHoaDon.getValueAt(tblHoaDon.getSelectedRow(), 0).toString().trim();
        pnlTTSP.setVisible(true);
        lbTenSP.setText(xldh.lay1DL1BangcoDK("TenSP", "SanPham", "MaSP", maSP));
        lbNSX.setText(xldh.lay1DL1BangcoDK("HangSX", "SanPham", "MaSP", maSP));
        lbNgayRaMat.setText(xldh.lay1DL1BangcoDK("NgayRaMat", "SanPham", "MaSP", maSP));
        lbBoNho.setText(xldh.lay1DL1BangcoDK("BoNho", "SanPham", "MaSP", maSP));
        lbXuatXu.setText(xldh.lay1DL1BangcoDK("XuatXu", "SanPham", "MaSP", maSP));

    }//GEN-LAST:event_btnXemTTSPActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if ((tblmodel.getRowCount()) < 1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa tạo sản phẩm, vui lòng tạo ít nhất 1 sản phẩm !");
            return;
        }
        if (tblHoaDon.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng click chọn 1 dòng trong table !");
            return;
        } else {
            String SLthaydoi = JOptionPane.showInputDialog(this, "Nhập số lượng cần thay đổi", "Thông báo", JOptionPane.QUESTION_MESSAGE);

            while (SLthaydoi.equals("")) {
                JOptionPane.showMessageDialog(this, "Không được để trống !");
                SLthaydoi = JOptionPane.showInputDialog(this, "Nhập số lượng cần thay đổi", "Thông báo", JOptionPane.QUESTION_MESSAGE);
            }

            if (Integer.valueOf(SLthaydoi) <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng nhập vào phải lớn hơn 0 !");
                return;
            }
            tblmodel.setValueAt(SLthaydoi, tblHoaDon.getSelectedRow(), 2);

            int giaBan = Integer.valueOf(xldh.xoaPhay(tblmodel.getValueAt(tblHoaDon.getSelectedRow(), 4).toString()).trim());
            String ThTmoi = xldh.themPhay(String.valueOf((Integer.parseInt(SLthaydoi)) * giaBan));

            tblmodel.setValueAt(ThTmoi, tblHoaDon.getSelectedRow(), 5);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        if (xldh.huyDon()) {
            xldh.xoa1DongDL1BangcoDK("DonDatHang", "MaDH", xldh.lay1DLCuoi1Bang0DK("MaDH", "DonDatHang").trim());
            JOptionPane.showMessageDialog(this, "Hủy đơn hàng thành công !");
            this.setVisible(false);
            new FrLapHDBH(pq).setVisible(true);
        }

    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed

        int ques = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn tạo đơn hàng?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (ques == 0) {
            for (int i = 0; i < tblmodel.getRowCount(); i++) {
                String MaDH = lbMaDH.getText();
                String MaSP = tblmodel.getValueAt(i, 0).toString().trim();
                String SLMua = tblmodel.getValueAt(i, 2).toString().trim();
                String maHT = xldh.lay1DL1BangcoDK("MaBH", "ChinhSachBaoHanh", "TenCSBH", cbxHTBH1.getSelectedItem().toString().trim());
                xldh.them1SP(MaDH, MaSP, SLMua, maHT);
            }
            JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công, nhấn OK để xem chi tiết Đơn Hàng !");

            if (pq.getKey().equals("2")) {
                pq.setXacnhan("1");
                new FrXemCTDH(lbMaDH.getText(), pq, "2").setVisible(true);
            } else if (pq.getKey().equals("1")) {
                pq.setXacnhan(null);
                new FrXemCTDH(lbMaDH.getText(), pq, "1").setVisible(true);
            }
            this.setVisible(false);

        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void mnbTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnbTrangChuMouseClicked
        JOptionPane.showMessageDialog(this, "Bạn đang trong quá trình thêm sản phẩm, vui lòng chọn Button thoát phía dưới để hủy đơn hàng");
        JOptionPane.showMessageDialog(this, "Đăng xuất thất bại !");
    }//GEN-LAST:event_mnbTrangChuMouseClicked

    private void mnbTroGiupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnbTroGiupMouseClicked
        JOptionPane.showMessageDialog(this, "Liên hệ với quản lý để được giải đáp thắc mắc " + "\n" + "Hotline: 19002821");
    }//GEN-LAST:event_mnbTroGiupMouseClicked

    private void mnbDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnbDangXuatMouseClicked
        JOptionPane.showMessageDialog(this, "Bạn đang trong quá trình thêm sản phẩm, vui lòng chọn Button thoát phía dưới để hủy đơn hàng");
        JOptionPane.showMessageDialog(this, "Đăng xuất thất bại !");

    }//GEN-LAST:event_mnbDangXuatMouseClicked

    private void mnbDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbDangXuatActionPerformed

    }//GEN-LAST:event_mnbDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrTaoCTDH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrTaoCTDH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrTaoCTDH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrTaoCTDH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrTaoCTDH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXemTTSP;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.JComboBox<String> cbxHTBH1;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBoNho;
    private javax.swing.JLabel lbDienThoaiKH;
    private javax.swing.JLabel lbGioiTinhKH;
    private javax.swing.JLabel lbHoTenKH;
    private javax.swing.JLabel lbMaDH;
    private javax.swing.JLabel lbNSX;
    private javax.swing.JLabel lbNgayRaMat;
    private javax.swing.JLabel lbNgaySinhKH;
    private javax.swing.JLabel lbTenSP;
    private javax.swing.JLabel lbXuatXu;
    private javax.swing.JMenu mnbDangXuat;
    private javax.swing.JMenu mnbTrangChu;
    private javax.swing.JMenu mnbTroGiup;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnlTTSP;
    private javax.swing.JSpinner spSL;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtMaSP;
    // End of variables declaration//GEN-END:variables
}
